version: '4'
services:
  visitors_service:
    build: visitors_service/
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./visitors_service/:/usr/src
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db

  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - redis:/data
  # sidekiq:
  #   build: .
  #   command: sidekiq
  #   volumes:
  #     - .:/usr/src
  #   environment:
  #     REDIS_URL: redis://redis:6379/0
  #   depends_on:
  #     - redis
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  # rabbit:
  # redis:

