version: '3'
services:
  tickets: 
    build: tickets
    command: sh -c "rm -f /usr/src/tmp/pids/server.pid && cd tickets && rails server -b 0.0.0.0"
    volumes:
      - .:/usr/src/tickets
    ports:
      - "3000:3000"
    depends_on:
      - tickets_db
  
  tickets_db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
      - .:/src/tickets/
volumes:
  postgres:
