version: '3'
services:

  redis:
    image: redis:alpine
    volumes:
    - redis:/data

  sidekiq:
    build: .
    command: sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/usr/src
    

  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   ports:
  #   - 15672:15672
  #   volumes:
  #   - rabbit:/var/lib/rabbitmq
  
  booking: 
    build: booking/
    command: rails s -b 0.0.0.0 
    environment:
      REDIS_URL: redis://redis:6379/0
      PORT: 3001
    volumes:
      - .:/usr/src
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  # rabbit:
  postgres:
  redis:
