version: '4'
services:
  visitors:
    build: visitors_service/
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./visitors_service/:/usr/src
    ports:
      - 3004:3004
    environment:
      PORT: 3004
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db

  tickets: 
    build: tickets/
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./tickets/:/usr/src/
    environment:
      PORT: 3002
    ports:
      - 3002:3002
    depends_on:
      - db

  payment:
    build: payment_service/
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./payment_service/:/usr/src
    ports:
      - 3003:3003
    environment:
      PORT: 3003
      REDIS_URL: redis://redis:6379/0
      CREATE_VISITOR_URL: http://visitors:3004/api/visitors
      FETCH_BOOKING_URL: http://booking:3001/api/bookings
      BUY_BOOKING_URL: http://booking:3001/api/bookings
      UPDATE_BOOKING_STATUS_URL: http://booking:3001/api/bookings
      REQUIRED_AGE: 13
    depends_on:
      - db
  
  tourniquet: 
    build: tourniquet/
    command: rails s -b 0.0.0.0 
    volumes:
      - ./tourniquet/:/usr/src
    ports:
      - 3005:3005
    environment:
      PORT: 3005
      PATH_TO_VISITOR_VALIDATE: http://visitors:3002/api/visitors/validate?
      PATH_TO_TICKET_BLOCK: http://tickets:3002/api/tickets/block?
      PATH_TO_TICKET_INFO: http://tickets:3002/api/tickets/info?
    depends_on:
      - db

  booking: 
    build: booking/
    command: rails s -b 0.0.0.0 
    environment:
      PORT: 3001
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./booking/:/usr/src
    ports:
      - 3001:3001
    depends_on:
      - db

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
  sidekiq:
    build: .
    command: sidekiq
    volumes:
      - ./booking/:/usr/src
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  redis:
