default: &default
  adapter: postgresql
  host: tourniquet_db
  user: user
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> 
  timeout: 5000

development:
  <<: *default 
  database: tourniquet-development

test:
  <<: *default
  database: tourniquet-test

production:
  <<: *default
  database: tourniquet-production
